---
title: "Calculating rifle vs. rifle success rates"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Calculating rifle vs. rifle success rates}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
#| label: setup-knitr
#| include: FALSE
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = TRUE,
  include = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>"
)
```

We want to replicate the results shown in the tweet below.

<blockquote class="twitter-tweet">

<p lang="en" dir="ltr">

Top 10 NA players at RIFLE vs. RIFLE fights in 2022 (phantom/vandal):<br><br>1. <a href="https://twitter.com/Cryocells_?ref_src=twsrc%5Etfw">@Cryocells_</a> (58%)<br>2. <a href="https://twitter.com/NiSMO_VAL?ref_src=twsrc%5Etfw">@NiSMO_VAL</a> (58%)<br>3. <a href="https://twitter.com/trentFPS?ref_src=twsrc%5Etfw">@trentFPS</a> (58%)<br>4. <a href="https://twitter.com/DerrekOW?ref_src=twsrc%5Etfw">@DerrekOW</a> (55%)<br>5. <a href="https://twitter.com/diceyzx?ref_src=twsrc%5Etfw">@diceyzx</a> (54%)<br>6. <a href="https://twitter.com/yay?ref_src=twsrc%5Etfw">@yay</a> (54%)<br>7. <a href="https://twitter.com/valyngod?ref_src=twsrc%5Etfw">@valyngod</a> (53%)<br>8. <a href="https://twitter.com/TenZOfficial?ref_src=twsrc%5Etfw">@TenZOfficial</a> (53%)<br>9. <a href="https://twitter.com/777eeiu?ref_src=twsrc%5Etfw">@777eeiu</a> (53%)<br>10. <a href="https://twitter.com/s0mcs?ref_src=twsrc%5Etfw">@s0mcs</a> (53%)<br><br>What surprises you?

</p>

--- Weltis (@WeltisGames) <a href="https://twitter.com/WeltisGames/status/1578931912516636672?ref_src=twsrc%5Etfw">October 9, 2022</a>

</blockquote>

```{=html}
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
```{r}
#| label: setup
library(valorantr)
library(dplyr)
library(tidyr)
library(purrr)
```

```{r}
#| label: load events
events <- load_valorant("events")
events_na_2022 <- events |> 
  inner_join(get_all_region_names(), by = "regionId") |> 
  filter(!grepl("2021", name)) |> 
  distinct(event_id = id, event_name = name)
glimpse(events_na_2022)
```

```{r}
#| label: load series
series <- load_valorant("series")
teams <- get_all_team_names()

series_na_2022 <- series |> 
  rename(event_id = eventId, start_date = startDate) |> 
  inner_join(
    events_na_2022,
    by = "event_id"
  ) |> 
  unnest_wider(c(team1, team2), names_sep = "_") |>
  select(
    series_id = id, 
    event_id, 
    team1_id,
    team1_name = team1_name,
    team2_id,
    team2_name = team2_name
  )
glimpse(series_na_2022)
```

```{r}
#| label: load matches
set_names_from_id_element <- function(x) {
  match_ids <- x |> map_int(~pluck(.x, "id"))
  x |> set_names(match_ids)
}
matches <- load_valorant("matches") |> set_names_from_id_element()
matches_na_2022 <- matches[names(matches) %in% as.character(series_na_2022$series_id)]
team_player_mapping <- matches_na_2022 |> 
  map_dfr(
    ~pluck(.x, "playerStats"),
    .id = "match_id"
  ) |> 
  distinct(match_id, team_number = teamNumber, player_id = playerId) |> 
  mutate(across(match_id, as.integer))

map_pluck_matches <- function(matches, element) {
  matches |> map_int(~pluck(.x, element))
}

match_team_mapping <- tibble(
  match_id = matches_na_2022 |> map_pluck_matches("id"),
  `1` = matches_na_2022 |> map_pluck_matches("team1Id"),
  `2` = matches_na_2022 |> map_pluck_matches("team2Id")
) |> 
  pivot_longer(
    -match_id,
    names_to = "team_number",
    values_to = "team_id"
  ) |> 
  mutate(
    across(team_number, as.integer)
  )

match_team_player_mapping <- team_player_mapping |> 
  inner_join(
    team_mapping |> 
      transmute(match_id, team_number, team_id), 
    by = c("match_id", "team_number")
  ) |> 
  select(-team_number)
```

```{r}
#| label: load match details
## the names for matches are series ids
## the names for match details are match ids (individual maps between two teams)
match_detail_ids_na_2022 <- matches_na_2022 |> map(~pluck(.x, "matches", "id")) |> flatten_int()
match_details <- load_valorant("match_details") |> set_names_from_id_element()
match_details_na_2022 <- match_details[names(match_details) %in% as.character(match_detail_ids_na_2022)]
```

```{r}
#| label: load events and economies
cleanly_pluck_from_match_details <- function(match_details, element) {
  match_details |> 
    map_dfr(~pluck(.x, element), .id = "match_id") |> 
    as_tibble()
}

match_events <- match_details_na_2022 |> cleanly_pluck_from_match_details("events")
econ <- match_details_na_2022 |> cleanly_pluck_from_match_details("economies")
```

```{r}
#| label: weapon kills
players <- load_valorant("players")
weapon_ids <- get_all_weapon_names() |>
  select(
    weapon_id = weaponId, 
    weapon = weaponName, 
    weapon_category = weaponCategory
  )

weapon_kills <- match_events |> 
  filter(!is.na(killId), damageType == "weapon") |> 
  transmute(
    across(match_id, as.integer),
    round_id = roundId,
    round_number = roundNumber,
    kill_id = killId,
    killer_id = playerId, 
    victim_id = referencePlayerId,
    killer_weapon_id = weaponId
  ) |> 
  ## data doesn"t list victim"s actual weapon, so we use what they bought in their loadout
  left_join(
    econ |> 
      transmute(
        across(match_id, as.integer),
        round_id = roundId,
        victim_id = playerId, 
        victim_weapon_id = weaponId
      ),
    by = c("match_id", "round_id", "victim_id")
  ) |> 
  left_join(
    match_team_player_mapping |> 
      select(
        match_id, 
        killer_id = player_id, 
        killer_team_id = team_id
      ),
    by = c("match_id", "killer_id")
  ) |> 
  left_join(
    match_team_player_mapping |> 
      select(
        match_id, 
        victim_id = player_id, 
        victim_team_id = team_id
      ),
    by = c("match_id", "victim_id")
  ) |>
  left_join(
    players |> select(killer_id = id, killer_ign = ign),
    by = "killer_id"
  ) |> 
  left_join(
    players |> select(victim_id = id, victim_ign = ign),
    by = "victim_id"
  ) |> 
  left_join(
    teams |> select(killer_team_id = id, killer_team_name = name),
    by = "killer_team_id"
  ) |> 
  left_join(
    teams |> select(victim_team_id = id, victim_team_name = name),
    by = "victim_team_id"
  ) |> 
  left_join(
    weapon_ids |> rename_all(~sprintf("killer_%s", .x)),
    by = "killer_weapon_id"
  ) |> 
  left_join(
    weapon_ids |> rename_all(~sprintf("victim_%s", .x)),
    by = "victim_weapon_id"
  )
glimpse(weapon_kills)
```

```{r}
rifle_rifle_win_rates_by_player <- bind_rows(
  weapon_kills |> mutate(ign = killer_ign, player_id = killer_id, is_killer = TRUE),
  weapon_kills |> mutate(ign = victim_ign, player_id = victim_id, is_killer = FALSE)
) |> 
  # filter(
  #   killer_weapon_category == "rifle" &
  #   victim_weapon_category == "rifle"
  # ) |> 
  filter(
    (killer_weapon %in% c("phantom", "vandal")) &
      (victim_weapon %in% c("phantom", "vandal"))
  ) |> 
  count(player_id, ign, is_killer, sort = TRUE) |> 
  group_by(player_id, ign) |> 
  mutate(total = sum(n), prop = n / total) |> 
  ungroup() |> 
  filter(is_killer) |>
  select(-is_killer) |> 
  arrange(desc(prop))
glimpse(rifle_rifle_win_rates_by_player)
```

```{r}
#| label: latest_player_team_mapping
latest_player_team_mapping <- match_team_player_mapping |> 
  group_by(player_id) |> 
  slice_max(match_id, n = 1, with_ties = FALSE) |> 
  ungroup() |> 
  select(player_id, team_id) |> 
  left_join(
    players |> select(player_id = id, ign),
    by = "player_id"
  ) |> 
  left_join(
    teams |> 
      select(team_id = id, latest_team = name),
    by = "team_id"
  )
```

```{r}
top_rifle_rifle_win_rates <- rifle_rifle_win_rates_by_player |> 
  filter(total >= 200) |> 
  inner_join(
    latest_player_team_mapping |> select(player_id, latest_team),
    by = "player_id"
  ) |> 
  transmute(
    rank = row_number(desc(prop)),
    ign,
    latest_team,
    n,
    total,
    prop
  )
top_rifle_rifle_win_rates |> head(20)
```
